"""Add short name ro rarity

Revision ID: 288ef51149db
Revises: cb0e73a130b
Create Date: 2014-07-08 13:18:49.676769

"""

# revision identifiers, used by Alembic.
revision = '288ef51149db'
down_revision = 'cb0e73a130b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rarity', sa.Column('short_name', sa.String(length=4), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rarity', 'short_name')
    ### end Alembic commands ###
