"""Added log table

Revision ID: 311939d34034
Revises: 4b69ab09b34d
Create Date: 2014-07-05 15:31:34.525726

"""

# revision identifiers, used by Alembic.
revision = '311939d34034'
down_revision = '4b69ab09b34d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_action_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_log'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_log')
    ### end Alembic commands ###
